(function(){'use strict';
const ADMIN_ID='9006977016', ADMIN_PASS='Lavk@23456';
function $(id){return document.getElementById(id)}
function showLogin(role){
 let m=$('loginBridgeModal');
 if(!m){m=document.createElement('div');m.id='loginBridgeModal';m.style='position:fixed;inset:0;background:rgba(15,23,42,.65);display:flex;align-items:center;justify-content:center;padding:20px;z-index:100000';m.innerHTML='<div style="background:#fff;width:min(440px,100%);border-radius:18px;padding:24px;position:relative"><button id="lbClose" style="position:absolute;right:15px;top:12px;border:0;background:#f1f5f9;border-radius:8px;padding:7px">✕</button><h2 id="lbTitle"></h2><input id="lbId" style="width:100%;padding:12px;margin:7px 0;border:1px solid #dbe3eb;border-radius:10px"><input id="lbPass" type="password" style="width:100%;padding:12px;margin:7px 0;border:1px solid #dbe3eb;border-radius:10px"><button id="lbLogin" style="width:100%;padding:13px;margin-top:10px;background:#ff5a1f;color:#fff;border:0;border-radius:10px;font-weight:800">Login</button><p id="lbMsg" style="color:#dc2626"></p></div>';document.body.appendChild(m);$('lbClose').onclick=()=>m.remove();$('lbLogin').onclick=doLogin}
$('lbTitle').textContent=role==='admin'?'Admin Login':'Worker Login';$('lbId').placeholder=role==='admin'?'Admin User ID':'Worker Mobile';$('lbPass').placeholder='Password';$('lbLogin').dataset.role=role;m.dataset.role=role;m.style.display='flex';$('lbId').focus()
}
async function doLogin(){const role=$('lbLogin').dataset.role,id=$('lbId').value.trim(),pass=$('lbPass').value;if(role==='admin'){if(id!==ADMIN_ID||pass!==ADMIN_PASS){$('lbMsg').textContent='Invalid Admin User ID or Password';return}localStorage.setItem('gig_admin_login','1');location.href=location.pathname+'?admin=1';return}
 let workers=[];try{workers=JSON.parse(localStorage.getItem('gig_india_state')||'{}').workers||[]}catch(e){};if(!workers.length){try{const r=await fetch('https://pkofzvbdeljsksecbqzg.supabase.co/rest/v1/gig_india_state?id=eq.1',{headers:{Accept:'application/json'}});if(r.ok){const a=await r.json();workers=(a[0]&&a[0].data&&a[0].data.workers)||[];localStorage.setItem('gig_india_state',JSON.stringify(a[0].data))}}catch(e){}}
const w=workers.find(x=>String(x.mobile)===id&&String(x.password)===pass);if(!w){$('lbMsg').textContent='Invalid Worker Mobile or Password';return}localStorage.setItem('gig_worker_login',w.id);location.href=location.pathname+'?worker='+encodeURIComponent(w.id)
}
window.openLogin=function(role){showLogin(role||'worker')};window.openWorkerSignup=function(){if(typeof window._originalWorkerSignup==='function')return window._originalWorkerSignup();showLogin('worker')};
function addAdminButton(){const a=document.querySelector('.actions');if(a&&!document.getElementById('bridgeAdminBtn')){const b=document.createElement('button');b.id='bridgeAdminBtn';b.className='btn dark';b.type='button';b.textContent='Admin Login';b.onclick=()=>showLogin('admin');a.appendChild(b)}}
function boot(){addAdminButton();if(new URLSearchParams(location.search).get('admin')==='1'&&localStorage.getItem('gig_admin_login')==='1'){if(typeof window.renderAdminPanel==='function')window.renderAdminPanel();else if(typeof window.showAdmin==='function')window.showAdmin();else document.body.insertAdjacentHTML('afterbegin','<div style="padding:30px;text-align:center"><h1>Admin Login Successful</h1><p>Admin portal loading...</p></div>')}const wid=new URLSearchParams(location.search).get('worker');if(wid){localStorage.setItem('gig_worker_login',wid);if(typeof window.renderWorkerPanel==='function')window.renderWorkerPanel(wid);else if(typeof window.showWorker==='function')window.showWorker(wid)}}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();})();
